# Generated by Django 4.2.19 on 2025-03-14 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='purchased_book_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
