# Generated by Django 4.2.19 on 2025-03-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_rename_topics_topic'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='purchased_books',
            field=models.ManyToManyField(blank=True, related_name='purchased_books', to='Store.bookstorepage'),
        ),
    ]
