# Generated by Django 4.2.19 on 2025-03-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_account_purchased_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='purchased_book_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
