# Generated by Django 4.2.19 on 2025-03-14 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_comment_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0003_alter_account_purchased_book_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='purchased_book_date',
        ),
        migrations.CreateModel(
            name='PurchasedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='Store.bookstorepage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
