# Generated by Django 4.2.19 on 2025-03-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_remove_account_purchased_book_date_purchasedbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchasedBook',
        ),
    ]
