# Generated by Django 4.2.19 on 2025-03-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_delete_purchasedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Birthdate'),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('child', 'Child'), ('adult', 'Adult'), ('author', 'Author')], default='child', max_length=10),
        ),
    ]
