# Generated by Django 4.2.19 on 2025-03-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_account_birthdate_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('child', 'Child Reader'), ('adult', 'Adult Reader'), ('author', 'Author')], default='adult', max_length=10),
        ),
    ]
