# Generated by Django 4.2.19 on 2025-03-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstorepage',
            name='chapter',
        ),
        migrations.AddField(
            model_name='bookstorepage',
            name='pages',
            field=models.IntegerField(default=0, verbose_name='Amount Of Pages'),
        ),
    ]
