# Generated by Django 4.2.19 on 2025-03-18 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstorepage',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
