# Generated by Django 4.2.19 on 2025-03-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_bookstorepage_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstorepage',
            name='wishlist',
        ),
    ]
