# Generated by Django 4.2.19 on 2025-03-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_remove_bookstorepage_chapter_bookstorepage_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstorepage',
            name='bookdescription',
            field=models.CharField(max_length=490, verbose_name='Book Description'),
        ),
    ]
