# Generated by Django 4.2.19 on 2025-03-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_rename_post_bookstorepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='bookstorepage',
            old_name='featured_image',
            new_name='bookcover',
        ),
        migrations.RenameField(
            model_name='bookstorepage',
            old_name='content',
            new_name='bookdescription',
        ),
        migrations.RenameField(
            model_name='bookstorepage',
            old_name='title',
            new_name='booktitle',
        ),
        migrations.RemoveField(
            model_name='bookstorepage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookstorepage',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='bookstorepage',
            name='slug',
        ),
        migrations.AddField(
            model_name='bookstorepage',
            name='authorname',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookstorepage',
            name='bookprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bookstorepage',
            name='bookrating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='bookstorepage',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookstorepage',
            name='topics',
            field=models.ManyToManyField(related_name='books', to='Store.topic'),
        ),
    ]
