# Generated by Django 4.2.19 on 2025-03-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_topic_rename_featured_image_bookstorepage_bookcover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstorepage',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
