# Generated by Django 4.2.19 on 2025-03-11 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_bookstorepage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstorepage',
            name='bookrating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='bookstorepage',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='books', to='Store.topic'),
        ),
    ]
