# Generated by Django 4.2.19 on 2025-03-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_purchasedbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchasedBook',
        ),
    ]
