# Generated by Django 4.2.19 on 2025-03-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_bookstorepage_bookrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstorepage',
            name='chapter',
            field=models.IntegerField(default=0),
        ),
    ]
