# Generated by Django 4.2.19 on 2025-03-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_bookstorepage_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fantasy', 'Fantasy'), ('sci_fi', 'Science Fiction'), ('romance', 'Romance'), ('mystery', 'Mystery'), ('non_fiction', 'Non-fiction')], max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookstorepage',
            name='genre',
        ),
        migrations.AddField(
            model_name='bookstorepage',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='books', to='Store.genre'),
        ),
    ]
