# Generated by Django 4.2.19 on 2025-03-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_genre_remove_bookstorepage_genre_bookstorepage_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstorepage',
            name='age_restriction',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Age Restriction (18+)'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('sci_fi', 'Science Fiction'), ('romance', 'Romance'), ('mystery', 'Mystery'), ('non_fiction', 'Non-fiction'), ('thriller', 'Thriller')], max_length=100, unique=True),
        ),
    ]
