# Generated by Django 4.2.19 on 2025-03-11 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_bookstorepage_age_restriction_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstorepage',
            name='bookprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Book Price'),
        ),
        migrations.AlterField(
            model_name='bookstorepage',
            name='bookrating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Book Rating'),
        ),
    ]
