# Generated by Django 4.2.19 on 2025-03-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_alter_bookstorepage_bookprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstorepage',
            name='authorname',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Author Name'),
        ),
        migrations.AlterField(
            model_name='bookstorepage',
            name='bookdescription',
            field=models.TextField(verbose_name='Book Description'),
        ),
        migrations.AlterField(
            model_name='bookstorepage',
            name='booktitle',
            field=models.CharField(max_length=200, unique=True, verbose_name='Book Title'),
        ),
        migrations.AlterField(
            model_name='bookstorepage',
            name='chapter',
            field=models.IntegerField(default=0, verbose_name='Amount Of Chapters'),
        ),
        migrations.AlterField(
            model_name='bookstorepage',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='books', to='Store.genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='bookstorepage',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='bookstorepage',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='books', to='Store.topic', verbose_name='Topics'),
        ),
    ]
