# Generated by Django 4.2.19 on 2025-03-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_alter_bookstorepage_authorname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstorepage',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='SYSTEM, DO NOT EDIT'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
