# Generated by Django 4.2.19 on 2025-03-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_topics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AlterField(
            model_name='bookstorepage',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='books', to='Store.topics', verbose_name='Topics'),
        ),
    ]
