# Generated by Django 4.2.19 on 2025-03-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_delete_topic_alter_bookstorepage_topics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
    ]
