# Generated by Django 4.2.19 on 2025-03-22 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('birthdate_author', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Child', 'Child Reader'), ('Adult', 'Adult Reader'), ('Author', 'Author')], default='Adult', max_length=10)),
                ('favorite_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.genre')),
                ('hidden_books', models.ManyToManyField(blank=True, related_name='hidden_by_books', to='Store.bookstorepage')),
                ('hidden_topics', models.ManyToManyField(blank=True, related_name='hidden_by_topics', to='Store.topic')),
                ('purchased_books', models.ManyToManyField(blank=True, related_name='purchased_books', to='Store.bookstorepage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlisted_books', models.ManyToManyField(blank=True, related_name='wishlisted_books', to='Store.bookstorepage')),
            ],
        ),
    ]
