# Generated by Django 4.2.19 on 2025-03-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purchased_books',
            field=models.ManyToManyField(blank=True, related_name='purchased_books', to='Store.bookstorepage'),
        ),
    ]
