# Generated by Django 4.2.19 on 2025-03-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_bookstorepage_bookdescription'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visible_books',
            field=models.ManyToManyField(blank=True, related_name='visible_to', to='Store.bookstorepage'),
        ),
    ]
