# Generated by Django 4.2.19 on 2025-03-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_purchased_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Child', 'Child Reader'), ('Adult', 'Adult Reader')], default='Adult', max_length=10),
        ),
    ]
