# Generated by Django 4.2.19 on 2025-03-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_bookstorepage_wishlist'),
        ('profile', '0005_profile_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_books', to='Store.bookstorepage'),
        ),
    ]
