# Generated by Django 4.2.19 on 2025-03-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_alter_profile_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='wishlist',
            new_name='wishlisted_books',
        ),
    ]
