# Generated by Django 4.2.19 on 2025-03-18 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_bookstorepage_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0007_rename_wishlist_profile_wishlisted_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(to='Store.bookstorepage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
