# Generated by Django 4.2.19 on 2025-03-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_bookstorepage_wishlist'),
        ('profile', '0008_customshelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hidden_books',
            field=models.ManyToManyField(blank=True, related_name='hidden_by_profiles', to='Store.bookstorepage'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hidden_topics',
            field=models.ManyToManyField(blank=True, related_name='hidden_by_profiles', to='Store.topic'),
        ),
    ]
