# Generated by Django 4.2.19 on 2025-03-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_bookstorepage_wishlist'),
        ('profile', '0009_profile_hidden_books_profile_hidden_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hidden_books',
            field=models.ManyToManyField(blank=True, related_name='hidden_by', to='Store.bookstorepage'),
        ),
    ]
