# Generated by Django 4.2.19 on 2025-03-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_bookstorepage_wishlist'),
        ('profile', '0011_delete_customshelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hidden_books',
            field=models.ManyToManyField(blank=True, related_name='hidden_by_books', to='Store.bookstorepage'),
        ),
    ]
