# Generated by Django 4.2.19 on 2025-03-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_bookstorepage_wishlist'),
        ('profile', '0012_alter_profile_hidden_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hidden_topics',
            field=models.ManyToManyField(blank=True, related_name='hidden_by_topics', to='Store.topic'),
        ),
    ]
