# Generated by Django 4.2.19 on 2025-03-20 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_bookstorepage_wishlist'),
        ('profile', '0013_alter_profile_hidden_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.genre'),
        ),
    ]
